In [ ]:

Soal UTS
# Data

company_detail_list = [
      {
          'name': 'Company 1',
          'domain': 'Retail',
          'country': 'United States'
      },
      {
          'name': 'Company 2',
          'domain': 'Technology',
          'country': 'United Kingdom'
      },
      {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'country': 'United States'
      }
  ]

employee_detail_list = [
     {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0005',
          'first_name': 'Ying Han',
          'last_name': 'Tan',
          'full_name': 'Ying Han Tan',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0015',
          'first_name': 'Kenneth',
          'last_name': 'Ng',
          'full_name': 'Kenneth Ng',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0018',
          'first_name': 'Rubby',
          'last_name': 'Lee',
          'full_name': 'Rubby Lee',
          'company': 'Company 2',
          'nationality': 'Hong Kong'
      },
     {
          'name': 'EMP-0017',
          'first_name': 'Robert',
          'last_name': 'White',
          'full_name': 'Robert White',
          'company': 'Company 1',
          'nationality': 'United Kingdom'
      }
  ]
The next few cells will show some examples on how to interact with our functions. Note that some of these function calls could be useful for you in completing the tasks below.

Task 1
Please get the list of all Companies and sort by Company Name in reverse order.

Expected result:

[{
    "name": "Company 3"
}, {
    "name": "Company 2"
}, {
    "name": "Company 1"
}]
Soal 2
Please print all Domain value in every company (use print statement).

Expected return:

    Company 1: Retail (United States)
    Company 2: Technology (United Kingdom)
    Company 3: Healthcare (United States)
Task 3
List all Employees work By company domain.

Expected return:

{
    "Retail": [
         "John Doe",
         "Robert White",
         "Ying Han Tan"
     ],
    "Technology":[
          "Tom Smith",
          "Rubby Lee",
     ],
    "Healthcare": [
         "Kenneth Ng",
         "Andrew Sebastian"
     ],
}
Task 4
Create a function that return employees with it's company country.

Expected return:

[{
    "full_name": "John Doe",
    "company": "Company 1",
    "country": "United States"
}, {
    "full_name": "Tom Smith",
    "company": "Company 2",
    "country": "United Kingdom"
}, {
    "full_name": "Andrew Sebastian",
    "company": "Company 3",
    "country": "United Kingdom"
},  {
    "full_name": "Ying Han Tan",
    "company": "Company 1",
    "country": "United States"
},  {
    "full_name": "Kenneth Ng",
    "company": "Company 3",
    "country": "United States"
},  {
    "full_name": "Rubby Lee",
    "company": "Company 2",
    "country": "United Kingdom"
},   {
    "full_name": "Robert White",
    "company": "Company 1",
    "country": "United States"
},
    
]
Task 5
Create a function that return companies with a number of employees nationality that are working in the company.

Expected return:

[{
    "company": "Company 1",
    "employee_nationality": {
        "Australia": 2,
        "Hong Kong": 1
    }
}, {
    "company": "Company 2",
    "employee_nationality": {
        "Hong Kong": 1,
        "United States": 1
    }
}, {
    "company": "Company 3",
    "employee_nationality": {
        "United States": 2
    }
}]

In [14]:
import json

def get_sorted_companies(company_list):
    # Sort perusahaan berdasarkan nama dalam urutan terbalik
    sorted_companies = sorted(company_list, key=lambda x: x['name'], reverse=True)
    
    # Format hasil hanya dengan nama perusahaan
    result = [{"name": company["name"]} for company in sorted_companies]
    
    return result

# Data perusahaan
company_detail_list = [
    {'name': 'Company 1', 'domain': 'Retail', 'country': 'United States'},
    {'name': 'Company 2', 'domain': 'Technology', 'country': 'United Kingdom'},
    {'name': 'Company 3', 'domain': 'Healthcare', 'country': 'United States'}
]

# Jalankan fungsi dan tampilkan hasil dalam format JSON yang terstruktur
output = get_sorted_companies(company_detail_list)
print(json.dumps(output, indent=4))

[
    {
        "name": "Company 3"
    },
    {
        "name": "Company 2"
    },
    {
        "name": "Company 1"
    }
]

In [3]:
def print_company_domains(company_list):
    for company in company_list:
        print(f"{company['name']}: {company['domain']} ({company['country']})")

print_company_domains(company_detail_list)

Company 1: Retail (United States)
Company 2: Technology (United Kingdom)
Company 3: Healthcare (United States)

In [9]:
import json

def list_employees_by_domain(company_list, employee_list):
    # Buat peta perusahaan ke domain
    company_domain_map = {company['name']: company['domain'] for company in company_list}
    
    # Buat dictionary untuk mengelompokkan karyawan berdasarkan domain
    domain_employee_map = {}
    
    for employee in employee_list:
        # Dapatkan domain perusahaan karyawan dari peta
        domain = company_domain_map.get(employee['company'], None)
        
        # Jika domain ditemukan, tambahkan karyawan ke domain yang sesuai
        if domain:
            if domain not in domain_employee_map:
                domain_employee_map[domain] = []
            domain_employee_map[domain].append(employee['full_name'])
    
    return domain_employee_map

# Data
company_detail_list = [
    {'name': 'Company 1', 'domain': 'Retail', 'country': 'United States'},
    {'name': 'Company 2', 'domain': 'Technology', 'country': 'United Kingdom'},
    {'name': 'Company 3', 'domain': 'Healthcare', 'country': 'United States'}
]

employee_detail_list = [
    {'name': 'EMP-0001', 'first_name': 'John', 'last_name': 'Doe', 'full_name': 'John Doe', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0002', 'first_name': 'Tom', 'last_name': 'Smith', 'full_name': 'Tom Smith', 'company': 'Company 2', 'nationality': 'United States'},
    {'name': 'EMP-0003', 'first_name': 'Andrew', 'last_name': 'Sebastian', 'full_name': 'Andrew Sebastian', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0005', 'first_name': 'Ying Han', 'last_name': 'Tan', 'full_name': 'Ying Han Tan', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0015', 'first_name': 'Kenneth', 'last_name': 'Ng', 'full_name': 'Kenneth Ng', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0018', 'first_name': 'Rubby', 'last_name': 'Lee', 'full_name': 'Rubby Lee', 'company': 'Company 2', 'nationality': 'Hong Kong'},
    {'name': 'EMP-0017', 'first_name': 'Robert', 'last_name': 'White', 'full_name': 'Robert White', 'company': 'Company 1', 'nationality': 'United Kingdom'}
]

# Jalankan fungsi dan tampilkan hasil dalam format JSON yang terstruktur
output = list_employees_by_domain(company_detail_list, employee_detail_list)
print(json.dumps(output, indent=4))

{
    "Retail": [
        "John Doe",
        "Ying Han Tan",
        "Robert White"
    ],
    "Technology": [
        "Tom Smith",
        "Rubby Lee"
    ],
    "Healthcare": [
        "Andrew Sebastian",
        "Kenneth Ng"
    ]
}

In [10]:
import json

def get_employees_with_company_country(company_list, employee_list):
    # Buat peta perusahaan ke negara
    company_country_map = {company['name']: company['country'] for company in company_list}
    
    # Buat daftar karyawan dengan informasi negara perusahaan mereka
    result = [
        {
            "full_name": emp["full_name"],
            "company": emp["company"],
            "country": company_country_map.get(emp["company"], "Unknown")
        }
        for emp in employee_list
    ]
    return result

# Data
company_detail_list = [
    {'name': 'Company 1', 'domain': 'Retail', 'country': 'United States'},
    {'name': 'Company 2', 'domain': 'Technology', 'country': 'United Kingdom'},
    {'name': 'Company 3', 'domain': 'Healthcare', 'country': 'United States'}
]

employee_detail_list = [
    {'name': 'EMP-0001', 'first_name': 'John', 'last_name': 'Doe', 'full_name': 'John Doe', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0002', 'first_name': 'Tom', 'last_name': 'Smith', 'full_name': 'Tom Smith', 'company': 'Company 2', 'nationality': 'United States'},
    {'name': 'EMP-0003', 'first_name': 'Andrew', 'last_name': 'Sebastian', 'full_name': 'Andrew Sebastian', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0005', 'first_name': 'Ying Han', 'last_name': 'Tan', 'full_name': 'Ying Han Tan', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0015', 'first_name': 'Kenneth', 'last_name': 'Ng', 'full_name': 'Kenneth Ng', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0018', 'first_name': 'Rubby', 'last_name': 'Lee', 'full_name': 'Rubby Lee', 'company': 'Company 2', 'nationality': 'Hong Kong'},
    {'name': 'EMP-0017', 'first_name': 'Robert', 'last_name': 'White', 'full_name': 'Robert White', 'company': 'Company 1', 'nationality': 'United Kingdom'}
]

# Jalankan fungsi dan tampilkan hasil dalam format JSON yang terstruktur
output = get_employees_with_company_country(company_detail_list, employee_detail_list)
print(json.dumps(output, indent=4))

[
    {
        "full_name": "John Doe",
        "company": "Company 1",
        "country": "United States"
    },
    {
        "full_name": "Tom Smith",
        "company": "Company 2",
        "country": "United Kingdom"
    },
    {
        "full_name": "Andrew Sebastian",
        "company": "Company 3",
        "country": "United States"
    },
    {
        "full_name": "Ying Han Tan",
        "company": "Company 1",
        "country": "United States"
    },
    {
        "full_name": "Kenneth Ng",
        "company": "Company 3",
        "country": "United States"
    },
    {
        "full_name": "Rubby Lee",
        "company": "Company 2",
        "country": "United Kingdom"
    },
    {
        "full_name": "Robert White",
        "company": "Company 1",
        "country": "United States"
    }
]

In [12]:
import json

def get_company_employee_nationality_count(company_list, employee_list):
    # Buat dictionary untuk menyimpan jumlah kebangsaan karyawan berdasarkan perusahaan
    company_nationality_count = {company['name']: {} for company in company_list}

    # Hitung jumlah kebangsaan karyawan untuk setiap perusahaan
    for employee in employee_list:
        company_name = employee['company']
        nationality = employee['nationality']
        
        # Update jumlah kebangsaan untuk perusahaan yang sesuai
        if nationality in company_nationality_count[company_name]:
            company_nationality_count[company_name][nationality] += 1
        else:
            company_nationality_count[company_name][nationality] = 1
    
    # Format hasil sesuai dengan struktur yang diinginkan
    result = [
        {
            "company": company,
            "employee_nationality": company_nationality_count[company]
        }
        for company in company_nationality_count
    ]
    
    return result

# Data
company_detail_list = [
    {'name': 'Company 1', 'domain': 'Retail', 'country': 'United States'},
    {'name': 'Company 2', 'domain': 'Technology', 'country': 'United Kingdom'},
    {'name': 'Company 3', 'domain': 'Healthcare', 'country': 'United States'}
]

employee_detail_list = [
    {'name': 'EMP-0001', 'first_name': 'John', 'last_name': 'Doe', 'full_name': 'John Doe', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0002', 'first_name': 'Tom', 'last_name': 'Smith', 'full_name': 'Tom Smith', 'company': 'Company 2', 'nationality': 'United States'},
    {'name': 'EMP-0003', 'first_name': 'Andrew', 'last_name': 'Sebastian', 'full_name': 'Andrew Sebastian', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0005', 'first_name': 'Ying Han', 'last_name': 'Tan', 'full_name': 'Ying Han Tan', 'company': 'Company 1', 'nationality': 'Australia'},
    {'name': 'EMP-0015', 'first_name': 'Kenneth', 'last_name': 'Ng', 'full_name': 'Kenneth Ng', 'company': 'Company 3', 'nationality': 'United States'},
    {'name': 'EMP-0018', 'first_name': 'Rubby', 'last_name': 'Lee', 'full_name': 'Rubby Lee', 'company': 'Company 2', 'nationality': 'Hong Kong'},
    {'name': 'EMP-0017', 'first_name': 'Robert', 'last_name': 'White', 'full_name': 'Robert White', 'company': 'Company 1', 'nationality': 'United Kingdom'}
]

# Jalankan fungsi dan tampilkan hasil dalam format JSON yang terstruktur
output = get_company_employee_nationality_count(company_detail_list, employee_detail_list)
print(json.dumps(output, indent=4))

[
    {
        "company": "Company 1",
        "employee_nationality": {
            "Australia": 2,
            "United Kingdom": 1
        }
    },
    {
        "company": "Company 2",
        "employee_nationality": {
            "United States": 1,
            "Hong Kong": 1
        }
    },
    {
        "company": "Company 3",
        "employee_nationality": {
            "United States": 2
        }
    }
]